[package]
authors = ["Mohamad Mohebifar"]
edition = "2021"
license = "MIT"
name = "react_unforget_transform"
version = "0.1.0"
include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]
serde = { version = "1.0.189", features = ["derive"] }
swc_atoms = "0.6.5"
swc_common = "0.33.19"
swc_ecma_ast = "0.112.5"
swc_ecma_utils = "0.127.12"
swc_ecma_visit = "0.98.6"

[dev-dependencies]
serde_json = "1"
swc_ecma_parser = "0.143.9"
swc_ecma_transforms_base = "0.137.15"
swc_ecma_transforms = "0.229.16"
swc_ecma_transforms_testing = "0.140.15"
testing = "0.35.20"
